Script started on 2020-02-14 13:03:40-0500
]0;aaf25@gold24: ~/cs214/labs/02[01;32maaf25@gold24[00m:[01;34m~/cs214/labs/02[00m$ ma  cat example6.lex example. 6.y
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity		return TOKHUMIDITY;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */ 
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}
 
int yywrap() {
        return 1;
} 
 
int main() {
        yyparse();
} 

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
%%
commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
	| humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;

temperature_set: 
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;

humidity_set: 
        TOKSET TOKHUMIDITY NUMBER
        {
                printf("\tHumidity set to %d\n",$3);
        }
        ;
]0;aaf25@gold24: ~/cs214/labs/02[01;32maaf25@gold24[00m:[01;34m~/cs214/labs/02[00m$ make x example6. 
make: 'example6' is up to date.
]0;aaf25@gold24: ~/cs214/labs/02[01;32maaf25@gold24[00m:[01;34m~/cs214/labs/02[00m$ ./example6
d heat on
	Heat turned on
heat off
	Heat turned off
set termpa    mperature 6
	Temperature set to 6
set humidity 6
	Humidity set to 6
]0;aaf25@gold24: ~/cs214/labs/02[01;32maaf25@gold24[00m:[01;34m~/cs214/labs/02[00m$ exit

Script done on 2020-02-14 13:04:31-0500
